sELECT      COLUMN_NAME AS 'ColumnName'
            ,TABLE_NAME AS  'TableName'
FROM        INFORMATION_SCHEMA.COLUMNS
WHERE       COLUMN_NAME LIKE '%CARGAHORARIATOTALMINIMA%'
ORDER BY    TableName
            ,ColumnName;